ARG BASE_IMAGE=ct-ct-resolute-plain:main
FROM ${BASE_IMAGE}

RUN curl -fsSL https://claude.ai/install.sh | bash
# 安装 Claude Code VS Code 插件
RUN code-server --install-extension anthropic.claude-code

ENV PATH="/root/.local/bin:$PATH"
ENV PASSWORD=password

EXPOSE 8080

CMD ["code-server", "--auth", "password", "--host", "0.0.0.0", "--port", "8080"]
