FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    git \
    vim \
    nano \
    curl \
    zip \
    unzip \
    p7zip-full \
    ca-certificates \
    build-essential \
    bash-completion \
    software-properties-common \
    jq \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN curl -fsSL https://claude.ai/install.sh | bash
# 安装 Claude Code VS Code 插件
RUN code-server --install-extension anthropic.claude-code

ENV PATH="/root/.local/bin:$PATH"
ENV PASSWORD=password

EXPOSE 8080

CMD ["code-server", "--auth", "password", "--host", "0.0.0.0", "--port", "8080"]
